version: '3'

services:

  nk_sent2vec:
    build: .
    environment:
      - MODEL_PATH=/root/models/torontobooks_unigrams.bin
    volumes:
      - ./models:/root/models

  d3m_sent2vec:
    build: 
      dockerfile: d3m.dockerfile
      context: .
    environment:
      - MODEL_PATH=/root/models/torontobooks_unigrams.bin
    volumes:
      - ./models:/root/models
    