version: '3'

networks:
  backend:

services:

  nk_sent2vec:
    build: .
    environment:
      - MODEL_PATH=/root/models/torontobooks_unigrams.bin
    networks:
      - backend
    volumes:
      - ./models:/root/models